server:
  port: 8083
spring:
  data:
    mongodb:
      database: product-db
      host: localhost
      port: 27017

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 3000
    #initial-instance-info-replication-interval-seconds: 5
    service-url:
      defaultZone: http://${EUREKA-HOSTNAME:localhost}:${EUREKA-SERVER-PORT:8761}/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${random.int}
    lease-renewal-interval-in-seconds: 306
    lease-expiration-duration-in-seconds: 3000
