spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerDb?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      show-sql: true
      format-sql: true

    ## where resource server validate the token
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
##############################################################
